version: '3.8'

services:
  mindustry:
    image: jonathanlo411/mindustry-beta-server:latest
    container_name: mindustry-beta-server
    restart: unless-stopped
    
    stdin_open: true
    tty: true
    
    volumes:
      - mindustry-config:/opt/mindustry/config
    
    ports:
      - "6567:6567/tcp"
      - "6567:6567/udp"
      - "6859:6859/tcp"
    
    environment:
      CONFIG: /opt/mindustry/config

volumes:
  mindustry-config:
    driver: local
